"""
HTML output formatter - aman dari XSS.
Semua konten dari file yang di-scan di-escape sebelum ditampilkan.
"""

import html as html_module
from datetime import datetime, timezone

from .. import __version__


class HTMLFormatter:
    """Format hasil analisis sebagai HTML dengan escaping."""

    TEMPLATE = """<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>NusantaraScan Report</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 1000px; margin: 2rem auto; padding: 0 1rem; color: #222;
         line-height: 1.6; }}
  h1 {{ color: #1a5490; border-bottom: 2px solid #1a5490; padding-bottom: .5rem; }}
  h2 {{ color: #2c3e50; margin-top: 2rem; }}
  pre {{ background: #f4f4f4; padding: 1rem; border-radius: 6px;
         overflow-x: auto; border-left: 4px solid #1a5490;
         font-size: .9rem; }}
  .warn {{ color: #b00020; font-weight: bold; }}
  .ok {{ color: #0a7d2c; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  th, td {{ border: 1px solid #ddd; padding: .5rem; text-align: left;
            font-size: .9rem; }}
  th {{ background: #1a5490; color: white; }}
  .footer {{ margin-top: 3rem; font-size: .85rem; color: #888;
             border-top: 1px solid #eee; padding-top: 1rem; }}
  .badge {{ display: inline-block; padding: .2rem .6rem; border-radius: 4px;
            font-size: .8rem; color: white; }}
  .badge-warn {{ background: #b00020; }}
  .badge-ok {{ background: #0a7d2c; }}
</style>
</head>
<body>
<h1>NusantaraScan Report</h1>
<p><em>Generated: {generated}</em></p>

<h2>File Information</h2>
<pre>{file_info}</pre>

<h2>Sections</h2>
{sections_table}

<h2>Imports</h2>
{imports}

<h2>Suspicious Strings</h2>
{strings_block}

<h2>YARA Matches</h2>
{yara_block}

<div class="footer">
  Generated by NusantaraScan v{version} -
  <a href="https://github.com/Lutfifakee-Project/NusantaraScan">GitHub</a>
</div>
</body>
</html>
"""

    @staticmethod
    def _esc(value) -> str:
        """Escape HTML entities - cegah XSS."""
        return html_module.escape(str(value), quote=True)

    @staticmethod
    def format(results: dict) -> str:
        file_info = (
            f"Target : {HTMLFormatter._esc(results.get('target', 'Unknown'))}\n"
            f"Size   : {results.get('size', 0):,} bytes\n"
            f"Type   : {HTMLFormatter._esc(results.get('file_type', 'Unknown'))}\n"
            f"MD5    : {HTMLFormatter._esc(results.get('md5', 'Unknown'))}\n"
            f"SHA1   : {HTMLFormatter._esc(results.get('sha1', 'Unknown'))}\n"
            f"SHA256 : {HTMLFormatter._esc(results.get('sha256', 'Unknown'))}\n"
            f"Entropy: {results.get('entropy', 0):.4f}"
        )

        sections = results.get("sections", [])
        if sections:
            rows = []
            for sec in sections:
                rows.append(
                    "<tr>"
                    f"<td>{HTMLFormatter._esc(sec.get('name', 'Unknown'))}</td>"
                    f"<td>{HTMLFormatter._esc(hex(sec.get('virtual_address', 0)))}</td>"
                    f"<td>{HTMLFormatter._esc(hex(sec.get('virtual_size', 0)))}</td>"
                    f"<td>{HTMLFormatter._esc(hex(sec.get('raw_size', 0)))}</td>"
                    f"<td>{sec.get('entropy', 0):.4f}</td>"
                    "</tr>"
                )
            sections_table = (
                "<table><thead><tr>"
                "<th>Name</th><th>Virtual Address</th><th>Virtual Size</th>"
                "<th>Raw Size</th><th>Entropy</th>"
                "</tr></thead><tbody>"
                + "".join(rows)
                + "</tbody></table>"
            )
        else:
            sections_table = "<p><em>Tidak ada section info.</em></p>"

        imports = results.get("imports", {})
        if imports:
            lines = []
            for dll, funcs in imports.items():
                lines.append(f"{HTMLFormatter._esc(dll)}")
                for fn in funcs:
                    lines.append(f"  - {HTMLFormatter._esc(fn)}")
            imports_html = "<pre>" + "\n".join(lines) + "</pre>"
        else:
            imports_html = "<p><em>Tidak ada imports.</em></p>"

        suspicious = results.get("suspicious_strings", [])
        if suspicious:
            strings_block = (
                '<p><span class="badge badge-warn">'
                f"{len(suspicious)} ditemukan"
                "</span></p><pre>"
                + HTMLFormatter._esc("\n".join(suspicious))
                + "</pre>"
            )
        else:
            strings_block = (
                '<p><span class="badge badge-ok">Bersih</span></p>'
            )

        yara = results.get("yara_matches", [])
        if yara:
            yara_block = (
                '<p><span class="badge badge-warn">'
                f"{len(yara)} rule matched"
                "</span></p><pre>"
                + HTMLFormatter._esc("\n".join(yara))
                + "</pre>"
            )
        else:
            yara_block = '<p><em>Tidak ada YARA match.</em></p>'

        return HTMLFormatter.TEMPLATE.format(
            generated=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
            version=__version__,
            file_info=file_info,
            sections_table=sections_table,
            imports=imports_html,
            strings_block=strings_block,
            yara_block=yara_block,
        )

    @staticmethod
    def save(results: dict, filepath: str):
        html = HTMLFormatter.format(results)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)